[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/_health"
to = "/index.html"
status = 200
force = true

[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
